### ISSUE TITLE
using async daemon's logger in sync function fails with LookupError

### ISSUE THREAD

**Issue by rtoma** [nolar/kopf#676]
## Long story short

I would to use an async daemon's logger in a sync function, but this fails with a LookupError.

## Description

Setting the stage. I am developing an operator that:

- Runs an async daemon, its code starts 1* async tasks and gathers
- Each task is a while loop that periodically resolves hostnames using dns.asyncresolver
- The resolve results are compared to a NetworkPolicy, if different the NetworkPolicy is updated. The k8s requests are done using pykube-ng.
- Afaik pykube-ng is not async ready, so I have extracted previous step into a function that I am executing in a thread executor, like this:

```
loop = asyncio.get_running_loop()
executor = concurrent.futures.ThreadPoolExecutor()
await loop.run_in_executor(executor, handle_hostname_iplist, ...., logger)
```

Now in that "handle_hostname_iplist" function I want to log events using the logger.

Any attempt fails with:

```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/rtoma/projects/dns-network-policy-operator/env/lib/python3.9/site-packages/kopf/engines/loggers.py", line 132, in emit
    posting.enqueue(
  File "/Users/rtoma/projects/dns-network-policy-operator/env/lib/python3.9/site-packages/kopf/engines/posting.py", line 60, in enqueue
    loop = event_queue_loop_var.get()
LookupError: <ContextVar name='event_queue_loop_var' at 0x10be18220>
Call stack:
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "dns_network_policy_operator.py", line 98, in handle_hostname_iplist
    logger.info(f'Updated NetworkPolicy {namespace}/{netpol_name}, last change was {since_lastmod:.2f} seconds ago.')
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1794, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1832, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/Users/rtoma/projects/dns-network-policy-operator/env/lib/python3.9/site-packages/kopf/engines/loggers.py", line 138, in emit
    self.handleError(record)
Message: 'Updated NetworkPolicy operators/allow-egress-auth.docker.io-jk8bd, last change was 62.83 seconds ago.'
Arguments: ()
```

Now I can work around this by using a vanilla `logging.getLogger()`, but I wonder if it is possible to use the available logger. I assume the issue is caused by an async / sync boundary, but since I am new to async python I can't be sure.

Since I have a workaround please don't spend too much / any time on this. Submitting this is my way of contributing to kopf as it may help other developers facing the same issue.

## Environment

* Kopf version: 
* Kubernetes version: 
* Python version: 
* OS/platform: 

<details><summary>Python packages installed</summary>

```
```
</details>

**Comment by nolar** [comment]
I can take a look tomorrow. But a quick answer is that you probably need to pass the  asyncio’s/contextvars’ context to every side-thread. Like this (2 lines): https://github.com/nolar/kopf/blob/1.29.2/kopf/reactor/invocation.py#L129-L130
