### ISSUE TITLE
Resource Observer has failed

### ISSUE THREAD

**Issue by gajananbhat** [nolar/kopf#812]
### Long story short

I have a K8s cluster with an App container that exposes REST APIs and a container that has an operator based on kopf.
I have exposed the App container as a headless service with ClusterIP set to None.

If I set the hostNetwork to True, kopf container is able to connect to API server. However, it cannot connect to the App container exposed over the headless service.

If I set the hostNetwork to False, I can ping the App container, but I get the Resource Observer failed error while trying to connect to the API server on port 443. Please see logs below.

Is there a way I can connect to the API server and the App container?

Thanks

### Logs

```none
[2021-08-02 07:32:19,088] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
[2021-08-02 07:32:19,091] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2021-08-02 07:32:19,091] kopf._core.engines.a [INFO    ] Initial authentication has finished.
[2021-08-02 07:34:29,427] kopf._core.reactor.r [ERROR   ] Resource observer has failed: Cannot connect to host 10.96.0.1:443 ssl:default [Connect call failed ('10.96.0.1', 443)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('10.96.0.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/observation.py", line 108, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/scanning.py", line 54, in scan_resources
    resources.update(await coro)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 560, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/scanning.py", line 91, in _read_new_apis
    rsp = await errors.parse_response(await context.session.get(url))
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.96.0.1:443 ssl:default [Connect call failed ('10.96.0.1', 443)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('10.96.0.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 57, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 115, in run
    vault=__controls.vault,
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 71, in run
    _command=_command,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 129, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 409, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/observation.py", line 108, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/scanning.py", line 54, in scan_resources
    resources.update(await coro)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 560, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/scanning.py", line 91, in _read_new_apis
    rsp = await errors.parse_response(await context.session.get(url))
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.96.0.1:443 ssl:default [Connect call failed ('10.96.0.1', 443)]
```

**Comment by gajananbhat** [comment]
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+1.0.3.el7", GitCommit:"c4e6408d5dbe991e41b694261ab7c4a778711b26", GitTreeState:"clean", BuildDate:"2020-08-12T19:49:23Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+1.0.1.el7", GitCommit:"6a0645b94becbac24c3cc95cd913a6e99ae8342f", GitTreeState:"clean", BuildDate:"2020-07-17T23:08:07Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}

Kopf version: 1.32.1

Python version: 3.7

**Comment by nolar** [comment]
Sorry, I do not see how this issue relates to Kopf. Kopf uses aiohttp, and aoiohttp uses the regular OS network connectivity. The issue seems related to the Kubernetes networking. Can you connect to the same endpoints (API & App) with e.g. curl/wget/netcat/etc? If yes, I can take a closer look on what is happening. If no, it is worth fixing in the cluster setup.

**Comment by gajananbhat** [comment]
Thanks for the quick response,Nolar.

Yes. I can run curl from the operator container and get a response from the App container if the hostNetwork is set to false.

**Comment by gajananbhat** [comment]
I also have the following RBAC settings:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gdb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gdb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gdb-operator
    namespace: default
```

**Comment by nolar** [comment]
> Yes. I can run curl from the operator container and get a response from the App container if the hostNetwork is set to false.

But can you also access the API with curl in the same mode? It would be the `kubernetes.default.svc` hostname, or the IP from the exception stack traces. E.g. `curl -i --insecure https://kubernetes.default.svc/`

**Comment by gajananbhat** [comment]
No, I can't access the API using curl in the same mode. It just hangs.
```
root@gdbo:/# curl -i --insecure https://kubernetes.default.svc/
^C

root@gdbo:/#  curl -i --insecure https://10.96.0.1/
^C

root@gdbo:/# ping kubernetes
PING kubernetes.default.svc.cluster.local (10.96.0.1) 56(84) bytes of data.
^C

--- kubernetes.default.svc.cluster.local ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 73ms

```

**Comment by gajananbhat** [comment]
It's resolved now.

It was a network issue. My system administrator had started firewalld. Disabling firewalld fixed the issue. 

I will have to find out what ports to open so that I can use this firewalld running.

**Comment by nolar** [comment]
Then it is not Kopf's issue and I cannot help here. It is rather of your cluster's networking. You can try searching for help in other places (not sure which ones fit better: Kubernetes Slack chats, StackOverflow, etc). If you cannot do this from CLI, Kopf (and any other operator/tool) will not be able to do this too.

**Comment by nolar** [comment]
Ah, sorry, wrote it first, then distracted, then posted — but too late. It is good that it is resolved.

**Comment by gajananbhat** [comment]
Thanks for helping out !!
