### ISSUE TITLE
Standalone/KUBECONFIG Authentication

### ISSUE THREAD

**Issue by ruckc** [nolar/kopf#823]
### Long story short

I am trying to write a new operator, while testing it externally to the cluster, but keep getting "No credentials were retrieved from the login handlers.".  

### Kopf version

1.33.0

### Kubernetes version

1.21.3

### Python version

3.9.6

### Code

```python
# __main__.py

import asyncio
import kopf
import logging

registry = kopf.OperatorRegistry()


@kopf.on.login()
async def login_fn(**kwargs):
    return kopf.login_with_kubeconfig()


@kopf.on.startup()
async def configure(settings: kopf.OperatorSettings, **_):
    settings.posting.level = logging.DEBUG


def main():
    asyncio.run(kopf.operator(
        registry=registry,
        clusterwide=True,
        standalone=True,
    ))


main()
```

### Logs

```none
(exampleoperator-mG79rY9K-py3.9) ruckc@laptop:~/Projects/ruck/exampleoperator$ python -m exampleoperator
Initial authentication has failed: no credentials were retrieved from the login handlers.
Resource observer has failed: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 28, in <module>
    main()
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 21, in main
    asyncio.run(kopf.operator(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 129, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 410, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_read_old_api() done, defined at /home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py:35> exception=LoginError('Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/')>
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 43, in _read_old_api
    rsp = await api.get('/api', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
(exampleoperator-mG79rY9K-py3.9) ruckc@omnixps:~/Projects/ruck/exampleoperator$ python -m exampleoperator
Initial authentication has failed: no credentials were retrieved from the login handlers.
Resource observer has failed: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 28, in <module>
    main()
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 21, in main
    asyncio.run(kopf.operator(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 129, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 410, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_read_old_api() done, defined at /home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py:35> exception=LoginError('Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/')>
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 43, in _read_old_api
    rsp = await api.get('/api', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
(exampleoperator-mG79rY9K-py3.9) ruckc@omnixps:~/Projects/ruck/exampleoperator$ python -m exampleoperator
Initial authentication has failed: no credentials were retrieved from the login handlers.
Resource observer has failed: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 28, in <module>
    main()
  File "/home/ruckc/Projects/ruck/exampleoperator/exampleoperator/__main__.py", line 21, in main
    asyncio.run(kopf.operator(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 129, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/running.py", line 410, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_core/reactor/observation.py", line 113, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter, settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 31, in scan_resources
    resources.update(await coro)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 68, in _read_new_apis
    rsp = await api.get('/apis', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_read_old_api() done, defined at /home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py:35> exception=LoginError('Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/')>
Traceback (most recent call last):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/scanning.py", line 43, in _read_old_api
    rsp = await api.get('/api', settings=settings, logger=logger)
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/clients/auth.py", line 43, in wrapper
    async for key, info, context in vault.extended(APIContext, 'contexts'):
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 155, in extended
    async for key, item in self._items():
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 188, in _items
    yielded_key, yielded_item = self.select()
  File "/home/ruckc/.cache/pypoetry/virtualenvs/exampleoperator-mG79rY9K-py3.9/lib/python3.9/site-packages/kopf/_cogs/structs/credentials.py", line 207, in select
    raise LoginError("Ran out of valid credentials. Consider installing "
kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
```

### Additional information

I get the same log output if the `@kopf.on.login()` or `@kopf.on.startup()` is commented out.  I have also tried moving my kubeconfig into the standard `.kube/config` and unsetting the variable, with no output change.

The authentication inside the kubeconfig is simple user/token.  The k8s cluster is a single node `microk8s`. I have `KUBECONFIG` environment variable set and pointed at a valid (works with `kubernetes` and `kubernetes_asyncio`) kubeconfig.

I have tried alternative kubernetes contexts, and received the identical error (though, those are AWS EKS clusters, which are not simple authentications).

**Comment by nolar** [comment]
Hello. That sounds strange. Rudimentary authentication should be supported out of the box with no helper libraries. And the helper libraries should make it even more supported (kind of; in extra "unusual" cases).

Can you try `kopf.login_via_client()` function instead? (If you have `kubernetes` or `kubernetes_asyncio` installed.)

Would it be a problem to share your full kubeconfig here? (But please replace the actual tokens/passwords with something fake.)

And when you say `.kube/config`, do you mean `~/.kube/config`?

Also, can you please clarify: do you run it on Ubuntu or other Linux or MacOS or Windows? (I'll try to reproduce it.)

**Comment by ruckc** [comment]
Ubuntu 21.04 with the microk8s snap (1.21.3).

i've tried the `kopf.login_via_client()` also, while installing the kubernetes package.  This is my kubeconfig with the cert and admin token scrubbed.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cert>
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: <token>
```

**Comment by ruckc** [comment]
.... hmm, user error.  turns out i was mixing up the guidance for embedding.  i had defined the operator registry on the `kopf.operator()` and the registry wasn't tied to my login handler.

```python
import asyncio
import kopf
import logging


@kopf.on.login()
def login_fn(**kwargs):
    logger = logging.getLogger("login")
    logger.level = logging.DEBUG
    return kopf.login_via_client(logger=logger)


asyncio.run(kopf.operator(
    clusterwide=True,
    standalone=True,
))
```

**Comment by nolar** [comment]
Oh, right. I didn't notice it. Either that way or you can pass `registry=...` to every handler explicitly.

**Comment by ruckc** [comment]
I didn't need the registry, it was just a copy+paste from the embedding doc.  I just need to control it's lifecycle a little better than `kopf run`
