### ISSUE TITLE
Resource observer has failed. Stopping the watch-stream for customresourcedefinitions.v1.apiextensions.k8s.io cluster-wide

### ISSUE THREAD

**Issue by pavanfhw** [nolar/kopf#839]
### Long story short

I only have a timer running in my kopf. Kopf starts, runs the timer once successfully and then crashes with the error  `Resource observer has failed: Expecting ':' delimiter: line 1 column 1966062 (char 1966061)`

### Kopf version

1.34.0

### Kubernetes version

1.18

### Python version

3.7.9

### Logs

```none
[2021-09-23 18:48:51,376] kopf.objects         [INFO    ] [whatsgate] Timer 'check_whatsgate_instances' succeeded.
[2021-09-23 18:48:52,442] kopf._cogs.clients.w [DEBUG   ] Stopping the watch-stream for customresourcedefinitions.v1.apiextensions.k8s.io cluster-wide.
[2021-09-23 18:48:52,442] kopf._core.reactor.r [ERROR   ] Resource observer has failed: Expecting ':' delimiter: line 1 column 1966062 (char 1966061)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/observation.py", line 134, in resource_observer
    insights=insights))
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/queueing.py", line 184, in watcher
    async for raw_event in stream:
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/watching.py", line 82, in infinite_watch
    async for raw_event in stream:
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/watching.py", line 163, in continuous_watch
    namespace=namespace,
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/fetching.py", line 31, in list_objs
    settings=settings,
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/api.py", line 121, in get
    return await response.json()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1113, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 1966062 (char 1966061)
[2021-09-23 18:48:52,443] kopf._core.reactor.r [DEBUG   ] Admission insights chain is cancelled.
[2021-09-23 18:48:52,443] kopf._core.reactor.r [DEBUG   ] Admission webhook server is cancelled.
[2021-09-23 18:48:52,443] kopf._core.reactor.r [DEBUG   ] Credentials retriever is cancelled.
[2021-09-23 18:48:52,443] kopf._core.reactor.r [DEBUG   ] Admission validating configuration manager is cancelled.
[2021-09-23 18:48:52,444] kopf._core.reactor.r [DEBUG   ] Poster of events is cancelled.
[2021-09-23 18:48:52,444] kopf._core.reactor.r [DEBUG   ] Admission mutating configuration manager is cancelled.
[2021-09-23 18:48:52,444] kopf._cogs.clients.w [DEBUG   ] Stopping the watch-stream for namespaces.v1 cluster-wide.
[2021-09-23 18:48:52,444] kopf._cogs.clients.w [DEBUG   ] Stopping the watch-stream for namespaces.v1 cluster-wide.
[2021-09-23 18:48:52,444] kopf._core.reactor.r [DEBUG   ] Daemon killer is cancelled.
[2021-09-23 18:48:52,444] kopf._core.reactor.r [DEBUG   ] Namespace observer is cancelled.
[2021-09-23 18:48:52,445] kopf._core.reactor.o [DEBUG   ] Streaming tasks are stopped: finishing normally; tasks left: set()
[2021-09-23 18:48:52,445] kopf._core.reactor.r [DEBUG   ] Multidimensional multitasker is cancelled.
[2021-09-23 18:48:52,445] kopf._core.reactor.r [DEBUG   ] Root tasks are stopped: finishing normally; tasks left: set()
[2021-09-23 18:48:52,445] kopf._core.reactor.r [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 57, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 115, in run
    vault=__controls.vault,
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 71, in run
    _command=_command,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 129, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/running.py", line 410, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 69, in guard
    await coro
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/observation.py", line 134, in resource_observer
    insights=insights))
  File "/usr/local/lib/python3.7/site-packages/kopf/_core/reactor/queueing.py", line 184, in watcher
    async for raw_event in stream:
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/watching.py", line 82, in infinite_watch
    async for raw_event in stream:
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/watching.py", line 163, in continuous_watch
    namespace=namespace,
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/fetching.py", line 31, in list_objs
    settings=settings,
  File "/usr/local/lib/python3.7/site-packages/kopf/_cogs/clients/api.py", line 121, in get
    return await response.json()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1113, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 1966062 (char 1966061)
```
```


### Additional information

_No response_

**Comment by nolar** [comment]
It’s interesting. My first assumption would be that apiservers return something which is not json (perhaps, html). Which is weird on its own, but let’s check. Can you please execute these commands and post what do they return (with private/secret parts removed) — with the same credentials/context or from the same pod where the operator runs?

```
kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions
kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=true
```

The latter one can be interrupted with CtrlC.

**Comment by pavanfhw** [comment]
The result of this commands are huge. But it seems ok.
`kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions` : https://gist.github.com/pavanfhw/0d94371c4203cd86f67fbda37f7ac886
`kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=true`: https://gist.github.com/pavanfhw/695548c9e76ac0ed90c2b6db7f43c45d

**Comment by pavanfhw** [comment]
I used an online JSON validator and it return that https://gist.github.com/pavanfhw/0d94371c4203cd86f67fbda37f7ac886 is a valid JSON. I understood by the error message that the response was not a JSON as expected. But it seems it is.

**Comment by nolar** [comment]
Hm. The response itself looks good and parseable. My next assumption would be that it is something with the HTTP/TCP streams: e.g. incomplete reads in the underlying aiohttp, or maybe some issues with HTTP chunked responses. I cannot help with any of these issues anyway. And I would assume that aiohttp is reliable in this case — as it is widely used in other applications. It is more likely to be an issue with the network setup leading to the same effects (incomplete reads).

So, having access to the cluster and with some knowledge of Kopf's internals, I would put breakpoints or prints around those stacktrace lines in `kopf/_cogs/clients/api.py:121` in `get()` or somewhere around (depends on Kopf's version), conditioned as `if ('apiextensions.k8s.io/v1/customresourcedefinitions' in url)` — and see what is the text output of the response (`t = await response.text()`) instead of its parsed JSON; especially at its ending — does it look like a finished JSON, or is it interrupted in the middle.

* https://github.com/nolar/kopf/blob/1.34.0/kopf/_cogs/clients/api.py#L120-L121

```python
def get(...):
    ...
    async with response:
        if 'apiextensions.k8s.io/v1/customresourcedefinitions' in url:
            t = await response.text()
            print(repr(t[-50:]))
        return await response.json()
```

---

Alternatively, without investigating the issue, you can also disable the problematic cluster observation:

```python
@kopf.on.startup()
def config(settings, **_):
    settings.scanning.disabled = True
```

This will prevent custom resource & namespace listing and watching at runtime, it will only keep the resource listing at startup time. But this will also disable namespace glob/pattern matching — if you use it.

However, if the assumption is correct, i.e. having this issue of incomplete reads at the TCP/HTTP level, it can happen to any other resource kind too — sooner or later. Especially when there are many resource objects of one kind, or they are large.

**Comment by pavanfhw** [comment]
Thjank you @nolar, I think I can use the workaround for now. Since my timer works ok disabling the scanning.
