### ISSUE TITLE
IndexError following walkthrough

### ISSUE THREAD

**Issue by rubyisbeautiful** [nolar/kopf#921]
### Long story short

Following the walkthrough, I was working on [diffs](https://kopf.readthedocs.io/en/stable/walkthrough/diffs/).  After applying the change, I was adding, removing labels to observe the results.  Eventually I ended up with: `IndexError: tuple index out of range`.  
I temporarily added logging to the `relabel` function and saw:
```
diff: (('add', (), None, {'foo': 'bar'}),)
status: {'create_fn': {'pvc-name': 'my-claim'}, 'kopf': {'progress': {'create_fn': {'failure': False, 'purpose': 'create', 'retries': 1, 'started': '2022-05-06T18:38:20.631652', 'stopped': '2022-05-06T18:38:20.670679', 'success': True}, 'relabel/metadata.labels': {'failure': False, 'purpose': 'create', 'retries': 0, 'started': '2022-05-06T18:38:20.631662', 'success': False}}}}
namespace: foo
```

The proposed doc update simply adds a conditional to check for when field may be `None`

### Kopf version

1.35.4

### Kubernetes version

1.21.11

### Python version

3.10.3

### Code

```python
labels_patch = {field[0]: new for op, field, old, new in diff}
```

### Logs

```none
[2022-05-06 13:37:30,544] kopf.objects         [DEBUG   ] [foo/my-claim] Handler 'relabel/metadata.labels' is invoked.
diff: (('add', (), None, {'foo': 'bar'}),)
status: {'create_fn': {'pvc-name': 'my-claim'}, 'kopf': {'dummy': '2022-05-06T18:37:30.422387', 'progress': {'create_fn': {'failure': False, 'purpose': 'create', 'retries': 1, 'started': '2022-05-06T18:25:27.524626', 'stopped': '2022-05-06T18:25:27.639514', 'success': True}, 'relabel/metadata.labels': {'delayed': '2022-05-06T18:37:30.421032', 'failure': False, 'message': 'tuple index out of range', 'purpose': 'create', 'retries': 12, 'started': '2022-05-06T18:25:27.525690', 'success': False}}}}
namespace: foo
[2022-05-06 13:37:30,547] kopf.objects         [ERROR   ] [foo/my-claim] Handler 'relabel/metadata.labels' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/Users/derp/.local/share/virtualenvs/playing-with-kopf-t8Jv1o98/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/Users/derp/.local/share/virtualenvs/playing-with-kopf-t8Jv1o98/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/Users/derp/.local/share/virtualenvs/playing-with-kopf-t8Jv1o98/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/Users/derp/.asdf/installs/python/3.10.3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/derp/apps/playing-with-kopf/src/ephemeral.py", line 39, in relabel
    # op, field, old, new
  File "/Users/derp/apps/playing-with-kopf/src/ephemeral.py", line 39, in <dictcomp>
    # op, field, old, new
IndexError: tuple index out of range
[2022-05-06 13:37:30,549] kopf.objects         [DEBUG   ] [foo/my-claim] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/relabel.metadata.labels': '{"started":"2022-05-06T18:25:27.525690","delayed":"2022-05-06T18:38:30.548752","purpose":"create","retries":13,"success":false,"failure":false,"message":"tuple index out of range"}', 'kopf.zalando.org/touch-dummy': None}}, 'status': {'kopf': {'progress': {'relabel/metadata.labels': {'started': '2022-05-06T18:25:27.525690', 'stopped': None, 'delayed': '2022-05-06T18:38:30.548752', 'purpose': 'create', 'retries': 13, 'success': False, 'failure': False, 'message': 'tuple index out of range', 'subrefs': None}}, 'dummy': None}}}
[2022-05-06 13:37:30,562] kopf.objects         [DEBUG   ] [foo/my-claim] Sleeping was skipped because of the patch, 59.99981 seconds left.
```

### Additional information

[PR submitted](https://github.com/nolar/kopf/pull/920)

**Comment by builtroller** [comment]
PR #920 does not address the underlying problem. The shape of the `diff` does not match the documentation in the tutorial: https://kopf.readthedocs.io/en/stable/walkthrough/diffs/#diffs. The structure for `diff` is incorrect:

## Observed Diff Object
`(('add', (), None, {'foo': 'bar'}),)`

## Expected Diff Object
`[('add', ('foo',), None, 'bar')]`

## Test Setup
```python
# partial ephemeral.py

@kopf.on.field("ephemeralvolumeclaims", field="metadata.labels")
def relabel(diff, status, namespace, logger, **kwargs):

    # log diff
    logger.info(diff)
    
    labels_patch = {field[0]: new for op, field, old, new in diff}
    pvc_name = status["create_fn"]["pvc-name"]
    pvc_patch = {"metadata": {"labels": labels_patch}}

    api = kubernetes.client.CoreV1Api()
    obj = api.patch_namespaced_persistent_volume_claim(
        namespace=namespace,
        name=pvc_name,
        body=pvc_patch,
    )
```

```yaml
# evc.yaml
apiVersion: kopf.dev/v1
kind: EphemeralVolumeClaim
metadata:
  name: my-claim
  labels:
    foo: bar
spec:
  size: 100M
```

## Test Output
```sh
# kopf output
[2022-05-26 15:35:22,878] kopf.objects         [INFO    ] [sandbox/my-claim] (('add', (), None, {'foo': 'bar'}),)
[2022-05-26 15:35:22,880] kopf.objects         [ERROR   ] [sandbox/my-claim] Handler 'relabel/metadata.labels' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/home/vscode/.local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/home/vscode/.local/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspaces/kopf/examples/tutorial/ephemeral.py", line 55, in relabel
    labels_patch = {field[0]: new for op, field, old, new in diff}
  File "/workspaces/kopf/examples/tutorial/ephemeral.py", line 55, in <dictcomp>
    labels_patch = {field[0]: new for op, field, old, new in diff}
IndexError: tuple index out of range
```

**Comment by rubyisbeautiful** [comment]
Thanks @builtroller.  I will redo it from scratch and verify.

**Comment by rubyisbeautiful** [comment]
@builtroller I re-did from scratch, following the documentation.  I get the same results.  Trying to parse your example and log, it looks like you're confirming what I see.

Your statement is correct, that the PR doesn't address the root issue, which is that the documentation is incorrectly describing the diff object.

I'm not sure if that's the expected diff and the documentation needs to be updated, or if the observed diff is incorrect.

**Comment by nolar** [comment]
> I'm not sure if that's the expected diff and the documentation needs to be updated, or if the observed diff is incorrect.

The right notation is this one — it clearly expresses that the whole `labels` field did not exist before (that is important for PRESENT & ABSENT field filters):

```
(('add', (), None, {'foo': 'bar'}),)
```

The documentation should be fixed — I would appreciate a PR for this.

But the `if field` change of #920 does not fix it, as I understand — it does not do the re-labelling when the 1st label is added to the original object — because the change/diff mentioned above will be ignored.

**Comment by rubyisbeautiful** [comment]
@nolar I've updated #920 to reflect the correct data structure, and removed the unneeded conditional in the relabel example
